### ISSUE TITLE
Setup unit tests, code coverage and Travis CI Integration

### ISSUE THREAD

**Issue by kabirbaidhya** [kabirbaidhya/webpack-file-preprocessor-plugin#13]
Setup unit tests, code coverage and Travis CI Integration. 

**Requirements**
 - Preferred Tools
   - mocha, chai or jest for tests and assertions
   - Travis for CI
 - Add few tests.

**Comment by anusha5695** [comment]
Hi i want to take this up

**Comment by kabirbaidhya** [comment]
Sure you can @anusha5695

**Comment by anusha5695** [comment]
Hi @kabirbaidhya , any specific reason for mocha and chai? Isn't jest a better option to consider.

**Comment by kabirbaidhya** [comment]
@anusha5695 No problem, you can go ahead and use jest. Nothing specific - it's just that I'm more familiar with them :).

**Comment by anusha5695** [comment]
Hi @kabirbaidhya : Can you please review the changes
