### ISSUE TITLE
Add an example project using the plugin to minify javascript

### ISSUE THREAD

**Issue by kabirbaidhya** [kabirbaidhya/webpack-file-preprocessor-plugin#17]
Add an example project using the plugin to minify javascript.

**Requirements:**
- Take reference from the existing example under `examples/` directory. Use similar conventions and code style.
- Use `yarn` instead of `npm`.
- Use any popular javascript minifier.

**Comment by anusha5695** [comment]
Is this open to be picked?

**Comment by kabirbaidhya** [comment]
@anusha5695 For sure it is. If you're willing to work on this, I'd suggest you also take [this](https://github.com/kabirbaidhya/webpack-file-preprocessor-plugin/tree/master/examples) for reference. Thanks!

**Comment by anusha5695** [comment]
Yes sure
