### ISSUE TITLE
Add an example project using the plugin to minify css.

### ISSUE THREAD

**Issue by kabirbaidhya** [kabirbaidhya/webpack-file-preprocessor-plugin#18]
Add an example project using the plugin to minify css.

**Requirements:**
- Take reference from the existing example under `examples/` directory. Use similar conventions and code style.
- Use `yarn` instead of `npm`.
- Use any popular css minifier.

**Comment by Bhavesh27** [comment]
i want to take this up.

**Comment by kabirbaidhya** [comment]
Done in #26.
