### ISSUE TITLE
Integrate CI build and code coverage badges in the README

### ISSUE THREAD

**Issue by kabirbaidhya** [kabirbaidhya/webpack-file-preprocessor-plugin#19]
**Requirements**
 - Add a travis and code coverage badges in the README. (Use a flag-square badge like these.)
  ![image](https://user-images.githubusercontent.com/3315763/67650875-c777ac00-f966-11e9-99d0-5ed4b091fd5d.png)

**Comment by anusha5695** [comment]
Hi @kabirbaidhya : I ll pick this

**Comment by anusha5695** [comment]
Hi @kabirbaidhya : Please find the changes
